// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyqvtkyckreoysydjemd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cXZ0a3lja3Jlb3lzeWRqZW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MjI0MDgsImV4cCI6MjA3NzI5ODQwOH0.IOtHILYlWjvCsRB4lS6t-QpqV9ZpQlIRPSQSOyKUENo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});